# base image
FROM node:9.6.1 AS build

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.1 -g --silent

#create production build
COPY . /usr/src/app
RUN npm run build

# start app
FROM nginx:1.16.0-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
#RUN rm /etc/nginx/conf.d/default.conf
#COPY dev /etc/nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]